drop table tblHistorico 
drop table tblMedicamento 
drop table tblVermifugo 
drop table tblVacina 
drop table tblAnimal 
drop table tblTelefone 
drop table tblTipoTelefone 
drop table tblEndereco 
drop table tblCidade 
drop table tblEstado 
drop table tblRaca 
drop table tblEspecie 
drop table tblSexo 
drop table tblProprietario 
