INSERT INTO tblEspecie (especie) VALUES ('Cão (Canis lupus familiaris)')
INSERT INTO tblEspecie (especie) VALUES ('Gato (Felis catus)')
INSERT INTO tblEspecie (especie) VALUES ('Aves domésticas / de companhia (psitacídeos e passeriformes)')
INSERT INTO tblEspecie (especie) VALUES ('Coelho (Oryctolagus cuniculus)')
INSERT INTO tblEspecie (especie) VALUES ('Roedores (porquinho-da-índia / guinea pig, camundongo, ratazana)')
INSERT INTO tblEspecie (especie) VALUES ('Hamster (várias espécies)')
INSERT INTO tblEspecie (especie) VALUES ('Furão / Doninha doméstica (Mustela putorius furo)')
INSERT INTO tblEspecie (especie) VALUES ('Répteis (cobras, lagartos, tartarugas)')
INSERT INTO tblEspecie (especie) VALUES ('Peixes ornamentais (água doce / marinho)')
INSERT INTO tblEspecie (especie) VALUES ('Equino / Cavalo')
INSERT INTO tblEspecie (especie) VALUES ('Bovino / Gado')
INSERT INTO tblEspecie (especie) VALUES ('Caprino / Ovino')
INSERT INTO tblEspecie (especie) VALUES ('Suíno doméstico (pequenos suínos/mini pigs)')
INSERT INTO tblEspecie (especie) VALUES ('Animais silvestres resgatados (aves silvestres, marsupiais, etc.)')
INSERT INTO tblEspecie (especie) VALUES ('Animais de exóticos diversos (anfíbios: sapos/ rãs)')
INSERT INTO tblEspecie (especie) VALUES ('Abelhas / Apicultura')
INSERT INTO tblEspecie (especie) VALUES ('Outros grandes (camelos, lhamas, etc.)')
