INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'SRD (Sem Raça Definida) / Vira-lata')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Labrador Retriever')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Golden Retriever')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Poodle (Toy / Miniatura / Standard)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Shih Tzu')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Pug')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Bulldog Francês (French Bulldog)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Yorkshire Terrier')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Dachshund (Salsicha)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'American Bully / Pit Bull / American Staffordshire')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Boxer')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Pastor Alemão (German Shepherd)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Rottweiler')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Border Collie')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Chihuahua')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Maltês')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Schnauzer (Miniatura / Standard)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Husky Siberiano')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Lhasa Apso')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Doberman')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Basset Hound')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Beagle')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Cocker Spaniel (Inglês / Americano)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Pomerânia (Pomeranian / Spitz)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Akita Inu')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Bernese Mountain Dog')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Shiba Inu')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'English Springer Spaniel')
INSERT INTO tblRaca (idEspecie, raca) VALUES (1, 'Pitbull (classificações locais)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'SRD (Sem Raça Definida) / Vira-lata')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Siamês')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Persa')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Maine Coon')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Ragdoll')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Bengal')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Scottish Fold')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Sphynx')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'British Shorthair')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Exótico (Exotic Shorthair)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Himalayan (Himalaio)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'American Shorthair')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Siberian (Siberiano)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (2, 'Norwegian Forest Cat (Gato da Noruega)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Calopsita (Nymphicus hollandicus) / Cockatiel')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Periquito (Melopsittacus undulatus) / Budgerigar')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Papagaio (diversas espécies: Amazona, Psittacus, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Papagaio-do-congo (African Grey)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Arara (macaw) — várias espécies (arara-azul, arara-vermelha, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Canário (canários domésticos) / Curió')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Agapornis (lovebirds)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Cacatua / Cockatoo')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Amazona (papagaios amazônicos)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Outras aves ornamentais (coleiro, curió, sabiá, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (3, 'Aves silvestres resgatadas (categoria separada em wildlife)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Coelho SRD / Comum')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Holland Lop / Lop (orelhas caídas)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'New Zealand (New Zealand White)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Rex (Rex rabbit)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Lionhead')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Angorá (Angora)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Dutch (Dutch rabbit)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (4, 'Outros')
INSERT INTO tblRaca (idEspecie, raca) VALUES (5, 'Porquinho-da-Índia (Guinea pig) — American / Abyssinian / Teddy / Silkie')
INSERT INTO tblRaca (idEspecie, raca) VALUES (5, 'Camundongo (mouse) — comum')
INSERT INTO tblRaca (idEspecie, raca) VALUES (5, 'Rato doméstico (rat) — hooded, albino, dumbo (variações)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (5, 'Gerbil (gerbílios) — ocasional')
INSERT INTO tblRaca (idEspecie, raca) VALUES (5, 'Outros roedores (degus, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (6, 'Hamster Sírio (Golden / Syrian)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (6, 'Hamster Anão Russo (Campbell / Winter White)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (6, 'Hamster Roborovski')
INSERT INTO tblRaca (idEspecie, raca) VALUES (6, 'Outros hamsters (chinês, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (7, 'Furão doméstico (Mustela putorius furo) — padrão (não subdividido por raças usualmente)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (7, 'Variedades de pelagem (Albino, Sable, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Tartaruga / Jabuti — (Tortoises & Turtles: Red-eared slider, Jabuti)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Iguana (Iguana iguana)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Cascavel / Serpentes venenosas — (atenção: geralmente não atendidas em clínicas comuns)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Jiboia / Boa constrictor')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Python (Ball python)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Corn snake (Pantherophis guttatus)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Lagartos pequenos — Bearded Dragon, Leopard Gecko (Eublepharis macularius)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (8, 'Outros répteis exóticos (geckos, agama, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Peixe Beta / Betta')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Guppy')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Neon tetra / Tetra (vários)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Goldfish (Carpa dourada)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Angelfish (Escalar)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Discus')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Cichlids (vários) / Oscars')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Peixes marinhos comuns (clownfish, tangs) — requer clínica com experiência marinha')
INSERT INTO tblRaca (idEspecie, raca) VALUES (9, 'Outros (aquários plantados, crustáceos ornamentais)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (10, 'Mangalarga Marchador')
INSERT INTO tblRaca (idEspecie, raca) VALUES (10, 'Quarto de Milha (Quarter Horse)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (10, 'Puro-sangue Inglês (Thoroughbred)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (10, 'Árabe (Arabian)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (10, 'Campolina / Brasileiro de Hipismo / Outros crioulos')
INSERT INTO tblRaca (idEspecie, raca) VALUES (10, 'Pônei / Mini-horse')
INSERT INTO tblRaca (idEspecie, raca) VALUES (11, 'Nelore / Zebu (raças de corte comuns no Brasil)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (11, 'Holandês (Holstein) — leiteiro')
INSERT INTO tblRaca (idEspecie, raca) VALUES (11, 'Outras raças (Brahman, Angus, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (12, 'Caprinos (Boer, Saanen, Alpine)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (12, 'Ovinos (Suffolk, Dorper, Merino)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (13, 'Porco doméstico / Mini pig (variedades comerciais)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (14, 'Aves silvestres (pardal, sabiá, bem-te-vi, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (14, 'Marsupiais (gambá, gambá-de-orelhas, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (14, 'Primatas (eventual, em centros de resgate)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (14, 'Morcegos (resgate/triagem)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (14, 'Réptil silvestre resgatado (jabuti nativo, etc.)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (15, 'Rãs / Sapos (anfíbios pet)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (15, 'Salamandras / Axolote (axolotl)')
INSERT INTO tblRaca (idEspecie, raca) VALUES (16, 'Colmeias / Apis mellifera — manejo/consultoria')
INSERT INTO tblRaca (idEspecie, raca) VALUES (17, 'Lhamas / Alpacas / Outros (atendimento especializado ou veterinário rural)')